server:
  port: 8080

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ISADb
    username: postgres
    password: ftn
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    database: POSTGRESQL
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: isaprojekat1@gmail.com
    password: bpyjrqpswdubdjrf
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true
      mail.smtp.ssl.trust: smtp.gmail.com
